apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymkhana-server-deployment
  labels:
    app: gymkhana-server-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gymkhana-server-api
  template:
    metadata:
      labels:
        app: gymkhana-server-api
    spec:
      containers:
      - name: gymkhana-server-api
        image: gymkhana-server-image:local
        ports:
        - containerPort: 8000